local Library = loadstring(game:HttpGetAsync'https://mrm7000.github.io/wally%20ui%20v3/library.lua')()
local Window = Library:CreateWindow("Example")
local Folder = Window:CreateFolder("Example Folder")
Folder:Label("Example Label",Color3.fromRGB(38,38,38),Color3.fromRGB(0,216,111))
Folder:Button("Example Button", function()
    print("Works!")
end)
Folder:Toggle("Example Toggle", function(bool)
   shared.Toggle = bool
   print(shared.Toggle) 
end)
Folder:Slider("Example Slider",16,50,16,function(value)
    print(value)
end)
Folder:Dropdown("Example Dropdown",{"A","B","C"},function(option)
    print(option)
end)
Folder:Box("Example Box Number","number",function(value)
    print(value)
end)
Folder:Box("Example Box String","string",function(value)
    print(value)
end)
Folder:DestroyGUI()
Folder:GuiSettings()
